SourceData:
    - Source: 1
      TYPEOF:
        - TYPE: API
          Duration: 30m
          URL: http://127.0.0.1:8888/UploadConfig
        - TYPE: KAFKA
          Duration: 45m
          IP: 127.0.0.1
          Port: "9092"
          TopicName: test1
      TransformationConfig:
        OutputFormat: 
          - Key: "CustomerID,cid,cusID"
            DisplayName: "User_ID"
            KeyType: "INT"
          - Key: "Email,mailid,email"
            DisplayName: "Email"
            KeyType: "STRING"